In [6]:
import pandas as pd
from selenium import webdriver
from bs4 import BeautifulSoup as bs
from datetime import datetime
import time
import random
import warnings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 10)

In [7]:
# Load the DataFrames
df = pd.read_csv('exports/stocks.csv')
df

                             stock_name stock_code
0     7-ELEVEN MALAYSIA HOLDINGS BERHAD       5250
1          ABF MALAYSIA BOND INDEX FUND     0800EA
2                    ABLE GLOBAL BERHAD       7167
3                      ABLEGROUP BERHAD       7086
4                     ABM FUJIYA BERHAD       5198
...                                 ...        ...
1008               YKGI HOLDINGS BERHAD       7020
1009                YLI HOLDINGS BERHAD       7014
1010                YNH PROPERTY BERHAD       3158
1011                    YONG TAI BERHAD       7066
1012       YOONG ONN CORPORATION BERHAD       5159

[1013 rows x 2 columns]

In [8]:
# Put it into a list called stock_code
stock_code = list(df['stock_code'])
stock_code

['5250',
 '0800EA',
 '7167',
 '7086',
 '5198',
 '03028',
 '7131',
 '0218',
 '0122',
 '1481',
 '5281',
 '9148',
 '7191',
 '7146',
 '0181',
 '6599',
 '5139',
 '5185',
 '7145',
 '0258',
 '7315',
 '7078',
 '0209',
 '5238',
 '2658',
 '7609',
 '5116',
 '5115',
 '2674',
 '0079',
 '2488',
 '1163',
 '03051',
 '5269',
 '5127',
 '5293',
 '5307',
 '5120',
 '03011',
 '1015',
 '7031',
 '6351',
 '7083',
 '0048',
 '4758',
 '0226',
 '6556',
 '5082',
 '5568',
 '5088',
 '7090',
 '5015',
 '6432',
 '0119',
 '7214',
 '7181',
 '7007',
 '0038',
 '0068',
 '7722',
 '7129',
 '0159',
 '0105',
 '4057',
 '7162',
 '7054',
 '03032',
 '6399',
 '0072',
 '8176',
 '7048',
 '5130',
 '7099',
 '5302',
 '03037',
 '8885',
 '5204',
 '7579',
 '6888',
 '5106',
 '7120',
 '2305',
 '5021',
 '7005',
 '03012',
 '0098',
 '5258',
 '7251',
 '1899',
 '6602',
 '0187',
 '5190',
 '3239',
 '3395',
 '5196',
 '4219',
 '5248',
 '9814',
 '7668',
 '0263',
 '6173',
 '5932',
 '0195',
 '6998',
 '5032',
 '0179',
 '5069',
 '0168',
 '9288',
 '7036',
 '8133',
 '2771',
 '5254',
 '6297',
 '5100',
 '9938',
 '0011',
 '4162',
 '7221',
 '7188',
 '5210',
 '1818',
 '03042',
 '2828',
 '7174',
 '0191',
 '2852',
 '7128',
 '5105',
 '5311',
 '5099',
 '5180',
 '0163',
 '5257',
 '03016',
 '2836',
 '03048',
 '0173',
 '7076',
 '03053',
 '7035',
 '03024',
 '0238',
 '0243',
 '5195',
 '8052',
 '8982',
 '7209',
 '5273',
 '7187',
 '1929',
 '5007',
 '5188',
 '5797',
 '7016',
 '1023',
 '7245',
 '5104',
 '7117',
 '7202',
 '7154',
 '03001',
 '7018',
 '7986',
 '0246',
 '5071',
 '2127',
 '7195',
 '5037',
 '8044',
 '8435',
 '0240',
 '0261',
 '5738',
 '5049',
 '6718',
 '8591',
 '5094',
 '7165',
 '5301',
 '0051',
 '9423',
 '7157',
 '5184',
 '7204',
 '4456',
 '3484',
 '0400GB',
 '5276',
 '8338',
 '5216',
 '5141',
 '5132',
 '7212',
 '5165',
 '0152',
 '7277',
 '6947',
 '0029',
 '0131',
 '7528',
 '5908',
 '7114',
 '5835',
 '5265',
 '7169',
 '0205',
 '7198',
 '1619',
 '0269',
 '03055',
 '7233',
 '7148',
 '3948',
 '3026',
 '03046',
 '5259',
 '0154',
 '3417',
 '0267',
 '2143',
 '8206',
 '5283',
 '0059',
 '3557',
 '0239',
 '0227',
 '5253',
 '0255',
 '5036',
 '7471',
 '0107',
 '0064',
 '8907',
 '5208',
 '8877',
 '9016',
 '5228',
 '0090',
 '9091',
 '6076',
 '03025',
 '7149',
 '5056',
 '8613',
 '7217',
 '7773',
 '03021',
 '0100',
 '5081',
 '6815',
 '7208',
 '7094',
 '0174',
 '5101',
 '0190',
 '5205',
 '7249',
 '0065',
 '2984',
 '7047',
 '5029',
 '6041',
 '5306',
 '0084',
 '7229',
 '2755',
 '8605',
 '5222',
 '6939',
 '0149',
 '03026',
 '3107',
 '0150',
 '9318',
 '0231',
 '7210',
 '0116',
 '5197',
 '0157',
 '9172',
 '5277',
 '3689',
 '0128',
 '9377',
 '0820EA',
 '7676',
 '7184',
 '5226',
 '9261',
 '0206',
 '5398',
 '5209',
 '0198',
 '0078',
 '0104',
 '3182',
 '4715',
 '2291',
 '3204',
 '7197',
 '0039',
 '0021',
 '7192',
 '1147',
 '5220',
 '7022',
 '5020',
 '7382',
 '5649',
 '2135',
 '03029',
 '5592',
 '0208',
 '0074',
 '0082',
 '0136',
 '9962',
 '5102',
 '3247',
 '1503',
 '0237',
 '7253',
 '3034',
 '5138',
 '2062',
 '7501',
 '5008',
 '5168',
 '0060',
 '5187',
 '7105',
 '3255',
 '5028',
 '5121',
 '0175',
 '4324',
 '5095',
 '5151',
 '7803',
 '0161',
 '5136',
 '3298',
 '0160',
 '5072',
 '5199',
 '8443',
 '0188',
 '5169',
 '9601',
 '5160',
 '5819',
 '5274',
 '1082',
 '3301',
 '0041',
 '5291',
 '0228',
 '0185',
 '5062',
 '7013',
 '5000',
 '5024',
 '8478',
 '4251',
 '5084',
 '5108',
 '5255',
 '9113',
 '03038',
 '03030',
 '9687',
 '0023',
 '5606',
 '5299',
 '5227',
 '5225',
 '0401GA',
 '3336',
 '5614',
 '7222',
 '7243',
 '0166',
 '2607',
 '9393',
 '0253',
 '0265',
 '7240',
 '5178',
 '5295',
 '0147',
 '6262',
 '3379',
 '0192',
 '1961',
 '5249',
 '5107',
 '7183',
 '8834',
 '0010',
 '1589',
 '5309',
 '5175',
 '7043',
 '7223',
 '0024',
 '4723',
 '8648',
 '4383',
 '7152',
 '0058',
 '5161',
 '5673',
 '8931',
 '0146',
 '0127',
 '8923',
 '03040',
 '6769',
 '7096',
 '3441',
 '5192',
 '8672',
 '0170',
 '5247',
 '0054',
 '7216',
 '3476',
 '7199',
 '0193',
 '0151',
 '7323',
 '6483',
 '0835EA',
 '0834EA',
 '7161',
 '7077',
 '9334',
 '0036',
 '0143',
 '6203',
 '7062',
 '6211',
 '5371',
 '0210',
 '5027',
 '0180',
 '5171',
 '5280',
 '9466',
 '5235SS',
 '2453',
 '7164',
 '5035',
 '6971',
 '7017',
 '0111',
 '4847',
 '7153',
 '0002',
 '5878',
 '9121',
 '1996',
 '0176',
 '5038',
 '2445',
 '6874',
 '2186',
 '6491',
 '7033',
 '9083',
 '5310',
 '5843',
 '8362',
 '0268',
 '7179',
 '0018',
 '3174',
 '1643',
 '9385',
 '9326',
 '8494',
 '5789',
 '9881',
 '9628',
 '8079',
 '0266',
 '5232',
 '6633',
 '7170',
 '0249',
 '3573',
 '7089',
 '03047',
 '6645',
 '4235',
 '8486',
 '0182',
 '5284',
 '8303',
 '8621',
 '7085',
 '5068',
 '5143',
 '0075',
 '9199',
 '0103',
 '1198',
 '0095',
 '7617',
 '7087',
 '3859',
 '8583',
 '8141',
 '5264',
 '1155',
 '3794',
 '3662',
 '3891',
 '5014',
 '1171',
 '5186',
 '5916',
 '5098',
 '5077',
 '0155',
 '3867',
 '1651',
 '4936',
 '6181',
 '0156',
 '03015',
 '1058',
 '3514',
 '5078',
 '7029',
 '0189',
 '5236',
 '03019',
 '4022',
 '6012',
 '5983',
 '7004',
 '0167',
 '03022',
 '5182',
 '5090',
 '4502',
 '3069',
 '5129',
 '3778',
 '1694',
 '5223',
 '8192',
 '5040',
 '7234',
 '5011',
 '0207',
 '2097',
 '03005',
 '6149',
 '0043',
 '7595',
 '5026',
 '5286',
 '0126',
 '5001',
 '0112',
 '7935',
 '5166',
 '7219',
 '5576',
 '3816',
 '9571',
 '8893',
 '6114',
 '0085',
 '0034',
 '03027',
 '0113',
 '0245',
 '6459',
 '0229',
 '5237',
 '0070',
 '5296',
 '5202',
 '0213',
 '0092',
 '5152',
 '3883',
 '5085',
 '5703',
 '3913',
 '3905',
 '9539',
 '0138',
 '5087',
 '0821EA',
 '0827EA',
 '0824EA',
 '0825EA',
 '5275',
 '7692',
 '0108',
 '5073',
 '0270',
 '0056',
 '2038',
 '0235',
 '4707',
 '0020',
 '7060',
 '0096',
 '7241',
 '7215',
 '7139',
 '0083',
 '0026',
 '03006',
 '0201',
 '03045',
 '5047',
 '5066',
 '5025',
 '4944',
 '5533',
 '0220',
 '0049',
 '0172',
 '7071',
 '7140',
 '3018',
 '5298',
 '9008',
 '5079',
 '03041',
 '5260',
 '0035',
 '0040',
 '0275',
 '0222',
 '0252',
 '7107',
 '4006',
 '5827',
 '5065',
 '5053',
 '0053',
 '0153',
 '7225',
 '7095',
 '6009',
 '7052',
 '4081',
 '1287',
 '3719',
 '8419',
 '5125',
 '5022',
 '0242',
 '3611',
 '9407',
 '1724',
 '5657',
 '2682',
 '0022',
 '6912',
 '0177',
 '5212',
 '5041',
 '6068',
 '6254',
 '5271',
 '4464',
 '0233',
 '5231',
 '9997',
 '7160',
 '8346',
 '0186',
 '7108',
 '7080',
 '8532',
 '5436',
 '8311',
 '5219',
 '0171',
 '5133',
 '3042',
 '5183',
 '5681',
 '6033',
 '8117',
 '7081',
 '5622',
 '0006',
 '1902',
 '9598',
 '7163',
 '7055',
 '5075',
 '9695',
 '7172',
 '6637',
 '7088',
 '5080',
 '03031',
 '4634',
 '7237',
 '0217',
 '4065',
 '8869',
 '9873',
 '7168',
 '7123',
 '0822EA',
 '0823EA',
 '0123',
 '7201',
 '8966',
 '0091',
 '5070',
 '0260',
 '7010',
 '1295',
 '8273',
 '0007',
 '6807',
 '7134',
 '0196',
 '7084',
 '7544',
 '0202',
 '7498',
 '0236',
 '5272',
 '7765',
 '03052',
 '9296',
 '5256',
 '03002',
 '5270',
 '03036',
 '0032',
 '0081',
 '7130',
 '0219',
 '7232',
 '0200',
 '9946',
 '0106',
 '0037',
 '9954',
 '1066',
 '5278',
 '7006',
 '5113',
 '2542',
 '9741',
 '03039',
 '8745',
 '8664',
 '03056',
 '8567',
 '0183',
 '9822',
 '0223',
 '5147',
 '03057',
 '7943',
 '0133',
 '5218',
 '7811',
 '4596',
 '5170',
 '9237',
 '5126',
 '5135',
 '5252',
 '5157',
 '5207',
 '0109',
 '7239',
 '0158',
 '7247',
 '0099',
 '4731',
 '8125',
 '7045',
 '7158',
 '0028',
 '0212',
 '7073',
 '4286',
 '5145',
 '0203',
 '0178',
 '7053',
 '03009',
 '9792',
 '2224',
 '5308',
 '5305',
 '9431',
 '5213',
 '5123',
 '5279',
 '5163',
 '7180',
 '0055',
 '0251',
 '5517',
 '7412',
 '5173',
 '6017',
 '0241',
 '7246',
 '0129',
 '4197',
 '5285',
 '5288',
 '4316',
 '5172',
 '9776',
 '7115',
 '7155',
 '03008',
 '7248',
 '03023',
 '7132',
 '0117',
 '0169',
 '03054',
 '0259',
 '0215',
 '5242',
 '0093',
 '4375',
 '5134',
 '0225',
 '0045',
 '5665',
 '1562',
 '0216',
 '7103',
 '6084',
 '03049',
 '5006',
 '0080',
 '6904',
 '7207',
 '2569',
 '03050',
 '3743',
 '0262',
 '5211',
 '5263',
 '5176',
 '0148',
 '0001',
 '03033',
 '7235',
 '7106',
 '03018',
 '6521',
 '5303',
 '7186',
 '6139',
 '9717',
 '7082',
 '1538',
 '0050',
 '7228',
 '5012',
 '7097',
 '7211',
 '2259',
 '8524',
 '5191',
 '4405',
 '2429',
 '5149',
 '5140',
 '0211',
 '0221',
 '2054',
 '5289',
 '2739',
 '0132',
 '7439',
 '7200',
 '0230',
 '4863',
 '5347',
 '9369',
 '7252',
 '0089',
 '8702',
 '0145',
 '5112',
 '9075',
 '7034',
 '0012',
 '7889',
 '7374',
 '7854',
 '5031',
 '8397',
 '5239',
 '0101',
 '7230',
 '7285',
 '5010',
 '5268',
 '7113',
 '03013',
 '5111',
 '7173',
 '7176',
 '0836EA',
 '0833EA',
 '0832EA',
 '0837EA',
 '0831EA',
 '0830EA',
 '0829EA',
 '0829EB',
 '0828EA',
 '7218',
 '5054',
 '0199',
 '0118',
 '5401',
 '9059',
 '5042',
 '0272',
 '5297',
 '5230',
 '5167',
 '4359',
 '7079',
 '7100',
 '03043',
 '0005',
 '1368',
 '5148',
 '0256',
 '7137',
 '7227',
 '4588',
 '03017',
 '7091',
 '0257',
 '5005',
 '2593',
 '2089',
 '7133',
 '0247',
 '5200',
 '5110',
 '7757',
 '5292',
 '7250',
 '6963',
 '5243',
 '4995',
 '0273',
 '0069',
 '0120',
 '0097',
 '7070',
 '0232',
 '0838EA',
 '0066',
 '5162',
 '5142',
 '0102',
 '7203',
 '5016',
 '7226',
 '3565',
 '9679',
 '0197',
 '7231',
 '0271',
 '5246',
 '5009',
 '0162',
 '0008',
 '6378',
 '7050',
 '7025',
 '4243',
 '5156',
 '5267',
 '7121',
 '0165',
 '0140',
 '0017',
 ...]

In [9]:
# Create an empty dataframe
div_info_final = pd.DataFrame()

# Connect/open to Chrome webdriver 
driver = webdriver.Chrome()
driver.implicitly_wait(60)

timeout_list = []
no_div=[]

for s in stock_code:
    status = ""

    try:
        # Connect/open the Chrome webdriver
        driver = webdriver.Chrome()
        driver.implicitly_wait(60)
        
        url = 'https://www.klsescreener.com/v2/stocks/view/' + stock_code
        driver.get(url) 
        content = driver.page_source
        soup = BeautifulSoup(content, 'html.parser')

        # Scrape table
        tables = soup.find_all('table')
        
        # Define a list to store the table data
        table_data_list = []

        for table in tables:
            table_data = []
            rows = table.find_all('tr')
            for row in rows:
                cols = row.find_all('td')
                cols = [col.text.strip() for col in cols]
                table_data.append(cols)
            table_data_list.append(table_data)

        # Find the table that contains column 'Payment Date'
        i = 0
        has_div = False
        while i < len(table_data_list) and not has_div:
            n = 0
            while n < len(table_data_list[i][0]):
                if 'Payment Date' in table_data_list[i][0][n]:
                    has_div = True
                n += 1
            i += 1

        if has_div:
            div_info2 = table_data_list[i]

            # Manipulate the table data as needed
            # Example: You can access the data like div_info2[row_index][col_index]

            # Filter data between two dates   
            filtered_data = []  # To store filtered data

            for row in div_info2:
                # Check if the row contains the payment date
                if 'Payment Date' in row:
                    header = row
                else:
                    financial_year = pd.to_datetime(row[0], format='%d %b %Y', errors='coerce')
                    if financial_year and start_date <= financial_year < end_date:
                        filtered_data.append(header + row)

            # Check whether the filtered data is empty
            if not filtered_data:
                status = 'N'
                print(f'Stock code: {stock_code} - no dividend info between {start_date} to {end_date}')
            else:
                status = 'Y'
                # Append the filtered data to the list
                dividend_info_list.append(filtered_data)
                print(f'Stock code: {stock_code} - yes')
        else:
            status = 'N'
            print(f'Stock code: {stock_code} - no dividend info')

    except Exception as e:
        print(f'Stock code: {stock_code} - Loading failed due to Timeout')
        print(e)

    # Program to generate a random number between 5 to 30
    # Importing the random module
    sec = random.randint(3, 8)

    # Program scrapping waiting time
    time.sleep(sec)  # seconds

Stock code: ['5250', '0800EA', '7167', '7086', '5198', '03028', '7131', '0218', '0122', '1481', '5281', '9148', '7191', '7146', '0181', '6599', '5139', '5185', '7145', '0258', '7315', '7078', '0209', '5238', '2658', '7609', '5116', '5115', '2674', '0079', '2488', '1163', '03051', '5269', '5127', '5293', '5307', '5120', '03011', '1015', '7031', '6351', '7083', '0048', '4758', '0226', '6556', '5082', '5568', '5088', '7090', '5015', '6432', '0119', '7214', '7181', '7007', '0038', '0068', '7722', '7129', '0159', '0105', '4057', '7162', '7054', '03032', '6399', '0072', '8176', '7048', '5130', '7099', '5302', '03037', '8885', '5204', '7579', '6888', '5106', '7120', '2305', '5021', '7005', '03012', '0098', '5258', '7251', '1899', '6602', '0187', '5190', '3239', '3395', '5196', '4219', '5248', '9814', '7668', '0263', '6173', '5932', '0195', '6998', '5032', '0179', '5069', '0168', '9288', '7036', '8133', '2771', '5254', '6297', '5100', '9938', '0011', '4162', '7221', '7188', '5210', '1818', '03042', '2828', '7174', '0191', '2852', '7128', '5105', '5311', '5099', '5180', '0163', '5257', '03016', '2836', '03048', '0173', '7076', '03053', '7035', '03024', '0238', '0243', '5195', '8052', '8982', '7209', '5273', '7187', '1929', '5007', '5188', '5797', '7016', '1023', '7245', '5104', '7117', '7202', '7154', '03001', '7018', '7986', '0246', '5071', '2127', '7195', '5037', '8044', '8435', '0240', '0261', '5738', '5049', '6718', '8591', '5094', '7165', '5301', '0051', '9423', '7157', '5184', '7204', '4456', '3484', '0400GB', '5276', '8338', '5216', '5141', '5132', '7212', '5165', '0152', '7277', '6947', '0029', '0131', '7528', '5908', '7114', '5835', '5265', '7169', '0205', '7198', '1619', '0269', '03055', '7233', '7148', '3948', '3026', '03046', '5259', '0154', '3417', '0267', '2143', '8206', '5283', '0059', '3557', '0239', '0227', '5253', '0255', '5036', '7471', '0107', '0064', '8907', '5208', '8877', '9016', '5228', '0090', '9091', '6076', '03025', '7149', '5056', '8613', '7217', '7773', '03021', '0100', '5081', '6815', '7208', '7094', '0174', '5101', '0190', '5205', '7249', '0065', '2984', '7047', '5029', '6041', '5306', '0084', '7229', '2755', '8605', '5222', '6939', '0149', '03026', '3107', '0150', '9318', '0231', '7210', '0116', '5197', '0157', '9172', '5277', '3689', '0128', '9377', '0820EA', '7676', '7184', '5226', '9261', '0206', '5398', '5209', '0198', '0078', '0104', '3182', '4715', '2291', '3204', '7197', '0039', '0021', '7192', '1147', '5220', '7022', '5020', '7382', '5649', '2135', '03029', '5592', '0208', '0074', '0082', '0136', '9962', '5102', '3247', '1503', '0237', '7253', '3034', '5138', '2062', '7501', '5008', '5168', '0060', '5187', '7105', '3255', '5028', '5121', '0175', '4324', '5095', '5151', '7803', '0161', '5136', '3298', '0160', '5072', '5199', '8443', '0188', '5169', '9601', '5160', '5819', '5274', '1082', '3301', '0041', '5291', '0228', '0185', '5062', '7013', '5000', '5024', '8478', '4251', '5084', '5108', '5255', '9113', '03038', '03030', '9687', '0023', '5606', '5299', '5227', '5225', '0401GA', '3336', '5614', '7222', '7243', '0166', '2607', '9393', '0253', '0265', '7240', '5178', '5295', '0147', '6262', '3379', '0192', '1961', '5249', '5107', '7183', '8834', '0010', '1589', '5309', '5175', '7043', '7223', '0024', '4723', '8648', '4383', '7152', '0058', '5161', '5673', '8931', '0146', '0127', '8923', '03040', '6769', '7096', '3441', '5192', '8672', '0170', '5247', '0054', '7216', '3476', '7199', '0193', '0151', '7323', '6483', '0835EA', '0834EA', '7161', '7077', '9334', '0036', '0143', '6203', '7062', '6211', '5371', '0210', '5027', '0180', '5171', '5280', '9466', '5235SS', '2453', '7164', '5035', '6971', '7017', '0111', '4847', '7153', '0002', '5878', '9121', '1996', '0176', '5038', '2445', '6874', '2186', '6491', '7033', '9083', '5310', '5843', '8362', '0268', '7179', '0018', '3174', '1643', '9385', '9326', '8494', '5789', '9881', '9628', '8079', '0266', '5232', '6633', '7170', '0249', '3573', '7089', '03047', '6645', '4235', '8486', '0182', '5284', '8303', '8621', '7085', '5068', '5143', '0075', '9199', '0103', '1198', '0095', '7617', '7087', '3859', '8583', '8141', '5264', '1155', '3794', '3662', '3891', '5014', '1171', '5186', '5916', '5098', '5077', '0155', '3867', '1651', '4936', '6181', '0156', '03015', '1058', '3514', '5078', '7029', '0189', '5236', '03019', '4022', '6012', '5983', '7004', '0167', '03022', '5182', '5090', '4502', '3069', '5129', '3778', '1694', '5223', '8192', '5040', '7234', '5011', '0207', '2097', '03005', '6149', '0043', '7595', '5026', '5286', '0126', '5001', '0112', '7935', '5166', '7219', '5576', '3816', '9571', '8893', '6114', '0085', '0034', '03027', '0113', '0245', '6459', '0229', '5237', '0070', '5296', '5202', '0213', '0092', '5152', '3883', '5085', '5703', '3913', '3905', '9539', '0138', '5087', '0821EA', '0827EA', '0824EA', '0825EA', '5275', '7692', '0108', '5073', '0270', '0056', '2038', '0235', '4707', '0020', '7060', '0096', '7241', '7215', '7139', '0083', '0026', '03006', '0201', '03045', '5047', '5066', '5025', '4944', '5533', '0220', '0049', '0172', '7071', '7140', '3018', '5298', '9008', '5079', '03041', '5260', '0035', '0040', '0275', '0222', '0252', '7107', '4006', '5827', '5065', '5053', '0053', '0153', '7225', '7095', '6009', '7052', '4081', '1287', '3719', '8419', '5125', '5022', '0242', '3611', '9407', '1724', '5657', '2682', '0022', '6912', '0177', '5212', '5041', '6068', '6254', '5271', '4464', '0233', '5231', '9997', '7160', '8346', '0186', '7108', '7080', '8532', '5436', '8311', '5219', '0171', '5133', '3042', '5183', '5681', '6033', '8117', '7081', '5622', '0006', '1902', '9598', '7163', '7055', '5075', '9695', '7172', '6637', '7088', '5080', '03031', '4634', '7237', '0217', '4065', '8869', '9873', '7168', '7123', '0822EA', '0823EA', '0123', '7201', '8966', '0091', '5070', '0260', '7010', '1295', '8273', '0007', '6807', '7134', '0196', '7084', '7544', '0202', '7498', '0236', '5272', '7765', '03052', '9296', '5256', '03002', '5270', '03036', '0032', '0081', '7130', '0219', '7232', '0200', '9946', '0106', '0037', '9954', '1066', '5278', '7006', '5113', '2542', '9741', '03039', '8745', '8664', '03056', '8567', '0183', '9822', '0223', '5147', '03057', '7943', '0133', '5218', '7811', '4596', '5170', '9237', '5126', '5135', '5252', '5157', '5207', '0109', '7239', '0158', '7247', '0099', '4731', '8125', '7045', '7158', '0028', '0212', '7073', '4286', '5145', '0203', '0178', '7053', '03009', '9792', '2224', '5308', '5305', '9431', '5213', '5123', '5279', '5163', '7180', '0055', '0251', '5517', '7412', '5173', '6017', '0241', '7246', '0129', '4197', '5285', '5288', '4316', '5172', '9776', '7115', '7155', '03008', '7248', '03023', '7132', '0117', '0169', '03054', '0259', '0215', '5242', '0093', '4375', '5134', '0225', '0045', '5665', '1562', '0216', '7103', '6084', '03049', '5006', '0080', '6904', '7207', '2569', '03050', '3743', '0262', '5211', '5263', '5176', '0148', '0001', '03033', '7235', '7106', '03018', '6521', '5303', '7186', '6139', '9717', '7082', '1538', '0050', '7228', '5012', '7097', '7211', '2259', '8524', '5191', '4405', '2429', '5149', '5140', '0211', '0221', '2054', '5289', '2739', '0132', '7439', '7200', '0230', '4863', '5347', '9369', '7252', '0089', '8702', '0145', '5112', '9075', '7034', '0012', '7889', '7374', '7854', '5031', '8397', '5239', '0101', '7230', '7285', '5010', '5268', '7113', '03013', '5111', '7173', '7176', '0836EA', '0833EA', '0832EA', '0837EA', '0831EA', '0830EA', '0829EA', '0829EB', '0828EA', '7218', '5054', '0199', '0118', '5401', '9059', '5042', '0272', '5297', '5230', '5167', '4359', '7079', '7100', '03043', '0005', '1368', '5148', '0256', '7137', '7227', '4588', '03017', '7091', '0257', '5005', '2593', '2089', '7133', '0247', '5200', '5110', '7757', '5292', '7250', '6963', '5243', '4995', '0273', '0069', '0120', '0097', '7070', '0232', '0838EA', '0066', '5162', '5142', '0102', '7203', '5016', '7226', '3565', '9679', '0197', '7231', '0271', '5246', '5009', '0162', '0008', '6378', '7050', '7025', '4243', '5156', '5267', '7121', '0165', '0140', '0017', '7003', '7178', '5048', '0025', '5300', '0248', '0086', '7293', '7020', '7014', '3158', '7066', '5159'] - Loading failed due to Timeout
can only concatenate str (not "list") to str

Stock code: ['5250', '0800EA', '7167', '7086', '5198', '03028', '7131', '0218', '0122', '1481', '5281', '9148', '7191', '7146', '0181', '6599', '5139', '5185', '7145', '0258', '7315', '7078', '0209', '5238', '2658', '7609', '5116', '5115', '2674', '0079', '2488', '1163', '03051', '5269', '5127', '5293', '5307', '5120', '03011', '1015', '7031', '6351', '7083', '0048', '4758', '0226', '6556', '5082', '5568', '5088', '7090', '5015', '6432', '0119', '7214', '7181', '7007', '0038', '0068', '7722', '7129', '0159', '0105', '4057', '7162', '7054', '03032', '6399', '0072', '8176', '7048', '5130', '7099', '5302', '03037', '8885', '5204', '7579', '6888', '5106', '7120', '2305', '5021', '7005', '03012', '0098', '5258', '7251', '1899', '6602', '0187', '5190', '3239', '3395', '5196', '4219', '5248', '9814', '7668', '0263', '6173', '5932', '0195', '6998', '5032', '0179', '5069', '0168', '9288', '7036', '8133', '2771', '5254', '6297', '5100', '9938', '0011', '4162', '7221', '7188', '5210', '1818', '03042', '2828', '7174', '0191', '2852', '7128', '5105', '5311', '5099', '5180', '0163', '5257', '03016', '2836', '03048', '0173', '7076', '03053', '7035', '03024', '0238', '0243', '5195', '8052', '8982', '7209', '5273', '7187', '1929', '5007', '5188', '5797', '7016', '1023', '7245', '5104', '7117', '7202', '7154', '03001', '7018', '7986', '0246', '5071', '2127', '7195', '5037', '8044', '8435', '0240', '0261', '5738', '5049', '6718', '8591', '5094', '7165', '5301', '0051', '9423', '7157', '5184', '7204', '4456', '3484', '0400GB', '5276', '8338', '5216', '5141', '5132', '7212', '5165', '0152', '7277', '6947', '0029', '0131', '7528', '5908', '7114', '5835', '5265', '7169', '0205', '7198', '1619', '0269', '03055', '7233', '7148', '3948', '3026', '03046', '5259', '0154', '3417', '0267', '2143', '8206', '5283', '0059', '3557', '0239', '0227', '5253', '0255', '5036', '7471', '0107', '0064', '8907', '5208', '8877', '9016', '5228', '0090', '9091', '6076', '03025', '7149', '5056', '8613', '7217', '7773', '03021', '0100', '5081', '6815', '7208', '7094', '0174', '5101', '0190', '5205', '7249', '0065', '2984', '7047', '5029', '6041', '5306', '0084', '7229', '2755', '8605', '5222', '6939', '0149', '03026', '3107', '0150', '9318', '0231', '7210', '0116', '5197', '0157', '9172', '5277', '3689', '0128', '9377', '0820EA', '7676', '7184', '5226', '9261', '0206', '5398', '5209', '0198', '0078', '0104', '3182', '4715', '2291', '3204', '7197', '0039', '0021', '7192', '1147', '5220', '7022', '5020', '7382', '5649', '2135', '03029', '5592', '0208', '0074', '0082', '0136', '9962', '5102', '3247', '1503', '0237', '7253', '3034', '5138', '2062', '7501', '5008', '5168', '0060', '5187', '7105', '3255', '5028', '5121', '0175', '4324', '5095', '5151', '7803', '0161', '5136', '3298', '0160', '5072', '5199', '8443', '0188', '5169', '9601', '5160', '5819', '5274', '1082', '3301', '0041', '5291', '0228', '0185', '5062', '7013', '5000', '5024', '8478', '4251', '5084', '5108', '5255', '9113', '03038', '03030', '9687', '0023', '5606', '5299', '5227', '5225', '0401GA', '3336', '5614', '7222', '7243', '0166', '2607', '9393', '0253', '0265', '7240', '5178', '5295', '0147', '6262', '3379', '0192', '1961', '5249', '5107', '7183', '8834', '0010', '1589', '5309', '5175', '7043', '7223', '0024', '4723', '8648', '4383', '7152', '0058', '5161', '5673', '8931', '0146', '0127', '8923', '03040', '6769', '7096', '3441', '5192', '8672', '0170', '5247', '0054', '7216', '3476', '7199', '0193', '0151', '7323', '6483', '0835EA', '0834EA', '7161', '7077', '9334', '0036', '0143', '6203', '7062', '6211', '5371', '0210', '5027', '0180', '5171', '5280', '9466', '5235SS', '2453', '7164', '5035', '6971', '7017', '0111', '4847', '7153', '0002', '5878', '9121', '1996', '0176', '5038', '2445', '6874', '2186', '6491', '7033', '9083', '5310', '5843', '8362', '0268', '7179', '0018', '3174', '1643', '9385', '9326', '8494', '5789', '9881', '9628', '8079', '0266', '5232', '6633', '7170', '0249', '3573', '7089', '03047', '6645', '4235', '8486', '0182', '5284', '8303', '8621', '7085', '5068', '5143', '0075', '9199', '0103', '1198', '0095', '7617', '7087', '3859', '8583', '8141', '5264', '1155', '3794', '3662', '3891', '5014', '1171', '5186', '5916', '5098', '5077', '0155', '3867', '1651', '4936', '6181', '0156', '03015', '1058', '3514', '5078', '7029', '0189', '5236', '03019', '4022', '6012', '5983', '7004', '0167', '03022', '5182', '5090', '4502', '3069', '5129', '3778', '1694', '5223', '8192', '5040', '7234', '5011', '0207', '2097', '03005', '6149', '0043', '7595', '5026', '5286', '0126', '5001', '0112', '7935', '5166', '7219', '5576', '3816', '9571', '8893', '6114', '0085', '0034', '03027', '0113', '0245', '6459', '0229', '5237', '0070', '5296', '5202', '0213', '0092', '5152', '3883', '5085', '5703', '3913', '3905', '9539', '0138', '5087', '0821EA', '0827EA', '0824EA', '0825EA', '5275', '7692', '0108', '5073', '0270', '0056', '2038', '0235', '4707', '0020', '7060', '0096', '7241', '7215', '7139', '0083', '0026', '03006', '0201', '03045', '5047', '5066', '5025', '4944', '5533', '0220', '0049', '0172', '7071', '7140', '3018', '5298', '9008', '5079', '03041', '5260', '0035', '0040', '0275', '0222', '0252', '7107', '4006', '5827', '5065', '5053', '0053', '0153', '7225', '7095', '6009', '7052', '4081', '1287', '3719', '8419', '5125', '5022', '0242', '3611', '9407', '1724', '5657', '2682', '0022', '6912', '0177', '5212', '5041', '6068', '6254', '5271', '4464', '0233', '5231', '9997', '7160', '8346', '0186', '7108', '7080', '8532', '5436', '8311', '5219', '0171', '5133', '3042', '5183', '5681', '6033', '8117', '7081', '5622', '0006', '1902', '9598', '7163', '7055', '5075', '9695', '7172', '6637', '7088', '5080', '03031', '4634', '7237', '0217', '4065', '8869', '9873', '7168', '7123', '0822EA', '0823EA', '0123', '7201', '8966', '0091', '5070', '0260', '7010', '1295', '8273', '0007', '6807', '7134', '0196', '7084', '7544', '0202', '7498', '0236', '5272', '7765', '03052', '9296', '5256', '03002', '5270', '03036', '0032', '0081', '7130', '0219', '7232', '0200', '9946', '0106', '0037', '9954', '1066', '5278', '7006', '5113', '2542', '9741', '03039', '8745', '8664', '03056', '8567', '0183', '9822', '0223', '5147', '03057', '7943', '0133', '5218', '7811', '4596', '5170', '9237', '5126', '5135', '5252', '5157', '5207', '0109', '7239', '0158', '7247', '0099', '4731', '8125', '7045', '7158', '0028', '0212', '7073', '4286', '5145', '0203', '0178', '7053', '03009', '9792', '2224', '5308', '5305', '9431', '5213', '5123', '5279', '5163', '7180', '0055', '0251', '5517', '7412', '5173', '6017', '0241', '7246', '0129', '4197', '5285', '5288', '4316', '5172', '9776', '7115', '7155', '03008', '7248', '03023', '7132', '0117', '0169', '03054', '0259', '0215', '5242', '0093', '4375', '5134', '0225', '0045', '5665', '1562', '0216', '7103', '6084', '03049', '5006', '0080', '6904', '7207', '2569', '03050', '3743', '0262', '5211', '5263', '5176', '0148', '0001', '03033', '7235', '7106', '03018', '6521', '5303', '7186', '6139', '9717', '7082', '1538', '0050', '7228', '5012', '7097', '7211', '2259', '8524', '5191', '4405', '2429', '5149', '5140', '0211', '0221', '2054', '5289', '2739', '0132', '7439', '7200', '0230', '4863', '5347', '9369', '7252', '0089', '8702', '0145', '5112', '9075', '7034', '0012', '7889', '7374', '7854', '5031', '8397', '5239', '0101', '7230', '7285', '5010', '5268', '7113', '03013', '5111', '7173', '7176', '0836EA', '0833EA', '0832EA', '0837EA', '0831EA', '0830EA', '0829EA', '0829EB', '0828EA', '7218', '5054', '0199', '0118', '5401', '9059', '5042', '0272', '5297', '5230', '5167', '4359', '7079', '7100', '03043', '0005', '1368', '5148', '0256', '7137', '7227', '4588', '03017', '7091', '0257', '5005', '2593', '2089', '7133', '0247', '5200', '5110', '7757', '5292', '7250', '6963', '5243', '4995', '0273', '0069', '0120', '0097', '7070', '0232', '0838EA', '0066', '5162', '5142', '0102', '7203', '5016', '7226', '3565', '9679', '0197', '7231', '0271', '5246', '5009', '0162', '0008', '6378', '7050', '7025', '4243', '5156', '5267', '7121', '0165', '0140', '0017', '7003', '7178', '5048', '0025', '5300', '0248', '0086', '7293', '7020', '7014', '3158', '7066', '5159'] - Loading failed due to Timeout
can only concatenate str (not "list") to str

KeyboardInterrupt:

In [6]:
div_info_final

,Announced,Financial Year,Subject,EX Date,Payment Date,Amount,Indicator,Unnamed: 7,Stock Code,Year,Status
0,13 Apr 2023,2022-12-31,Interim Dividend,10 May 2023,25 May 2023,0.054,Currency,View,5250,2022,Y
1,20 Apr 2022,2021-12-31,Interim Dividend,10 May 2022,27 May 2022,0.026,Currency,View,5250,2021,Y
2,15 Apr 2021,2020-12-31,Interim Dividend,05 May 2021,21 May 2021,0.016,Currency,View,5250,2020,Y
3,22 Apr 2020,2019-12-31,Interim Dividend,12 May 2020,28 May 2020,0.023,Currency,View,5250,2019,Y
4,29 Apr 2019,2018-12-31,Interim Dividend,09 May 2019,23 May 2019,0.024,Currency,View,5250,2018,Y
...,...,...,...,...,...,...,...,...,...,...,...
4461,25 Jun 2020,2020-06-30,Interim Dividend,28 Jul 2020,18 Aug 2020,0.015,Currency,View,5159,2020,Y
4462,21 Oct 2019,2019-06-30,Final Dividend,19 Dec 2019,17 Jan 2020,0.025,Currency,View,5159,2019,Y
4463,30 May 2019,2019-06-30,Interim Dividend,08 Jul 2019,26 Jul 2019,0.025,Currency,View,5159,2019,Y
4464,30 Oct 2018,2018-06-30,Final Dividend,19 Dec 2018,18 Jan 2019,0.020,Currency,View,5159,2018,Y
4465,24 May 2018,2018-06-30,Interim Dividend,05 Jul 2018,26 Jul 2018,0.020,Currency,View,5159,2018,Y

In [7]:
div_info_final = div_info_final.drop(['Unnamed: 7'], axis=1)
div_info_final

,Announced,Financial Year,Subject,EX Date,Payment Date,Amount,Indicator,Stock Code,Year,Status
0,13 Apr 2023,2022-12-31,Interim Dividend,10 May 2023,25 May 2023,0.054,Currency,5250,2022,Y
1,20 Apr 2022,2021-12-31,Interim Dividend,10 May 2022,27 May 2022,0.026,Currency,5250,2021,Y
2,15 Apr 2021,2020-12-31,Interim Dividend,05 May 2021,21 May 2021,0.016,Currency,5250,2020,Y
3,22 Apr 2020,2019-12-31,Interim Dividend,12 May 2020,28 May 2020,0.023,Currency,5250,2019,Y
4,29 Apr 2019,2018-12-31,Interim Dividend,09 May 2019,23 May 2019,0.024,Currency,5250,2018,Y
...,...,...,...,...,...,...,...,...,...,...
4461,25 Jun 2020,2020-06-30,Interim Dividend,28 Jul 2020,18 Aug 2020,0.015,Currency,5159,2020,Y
4462,21 Oct 2019,2019-06-30,Final Dividend,19 Dec 2019,17 Jan 2020,0.025,Currency,5159,2019,Y
4463,30 May 2019,2019-06-30,Interim Dividend,08 Jul 2019,26 Jul 2019,0.025,Currency,5159,2019,Y
4464,30 Oct 2018,2018-06-30,Final Dividend,19 Dec 2018,18 Jan 2019,0.020,Currency,5159,2018,Y
4465,24 May 2018,2018-06-30,Interim Dividend,05 Jul 2018,26 Jul 2018,0.020,Currency,5159,2018,Y

In [8]:
# Specify the file path where you want to save the CSV file
csv_file_path = 'exports/historicaldividends.csv'

# Use the to_csv() method to export the DataFrame to a CSV file
div_info_final.to_csv(csv_file_path, index=False)  # Set index=False to exclude the DataFrame index from the CSV

print(f"DataFrame saved to {csv_file_path}")

DataFrame saved to exports/historicaldividends.csv

In [31]:
df = pd.read_csv('exports/historicaldividends.csv')

In [32]:
# Assuming your DataFrame is named 'df'
columns_to_remove = ["Financial Year", "Subject", "Indicator", "Year", "Status"]
df = df.drop(columns=columns_to_remove)

In [33]:
# Convert 'Announced' column to datetime
df['Announced'] = pd.to_datetime(df['Announced'])
# Convert 'EX Date' and 'Payment Date' columns to datetime
df['EX Date'] = pd.to_datetime(df['EX Date'])
df['Payment Date'] = pd.to_datetime(df['Payment Date'])
# Convert 'Amount' column to numeric (float)
df['Amount'] = pd.to_numeric(df['Amount'], errors='coerce')  # 'coerce' will set non-numeric values to NaN

In [34]:
print(df.dtypes)

Announced       datetime64[ns]
EX Date         datetime64[ns]
Payment Date    datetime64[ns]
Amount                 float64
Stock Code              object
dtype: object

In [35]:
df = df.rename(columns={
    "Announced": "dAnnceDate",
    "EX Date": "dExDate",
    "Payment Date": "dPayDate",
    "Amount": "dAmount",
    "Stock Code": "stock_code"
})
df

     dAnnceDate    dExDate   dPayDate  dAmount stock_code
0    2023-04-13 2023-05-10 2023-05-25    0.054       5250
1    2022-04-20 2022-05-10 2022-05-27    0.026       5250
2    2021-04-15 2021-05-05 2021-05-21    0.016       5250
3    2020-04-22 2020-05-12 2020-05-28    0.023       5250
4    2019-04-29 2019-05-09 2019-05-23    0.024       5250
...         ...        ...        ...      ...        ...
4461 2020-06-25 2020-07-28 2020-08-18    0.015       5159
4462 2019-10-21 2019-12-19 2020-01-17    0.025       5159
4463 2019-05-30 2019-07-08 2019-07-26    0.025       5159
4464 2018-10-30 2018-12-19 2019-01-18    0.020       5159
4465 2018-05-24 2018-07-05 2018-07-26    0.020       5159

[4466 rows x 5 columns]

In [37]:
# Specify the file path where you want to save the CSV file
csv_file_path = 'exports/historicaldividends_cleaned.csv'

# Use the to_csv() method to export the DataFrame to a CSV file
df.to_csv(csv_file_path, index=False)  # Set index=False to exclude the DataFrame index from the CSV

print(f"DataFrame saved to {csv_file_path}")

DataFrame saved to exports/historicaldividends_cleaned.csv